export const ROOT_DRAWER: string = 'RootDrawer'
export const ROOT_MAIN_STACK: string = 'RootMainStack'
export const MAIN_SCREEN: string = 'MainScreen'
export const ARTICLE_NEWS: string = 'ArticleNews'
export const SIMS_SCREEN: string = 'SimsScreen'
export const YODA_SCREEN: string = 'YodaScreen'
export const CARD_SCREEN: string = 'CardScreen'
